[package]
name = "vtuve"
version = "0.1.0"
authors = ["fuyutarow <fuyutarow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.10.1"
